
name: Release
on: [push]
jobs:
    Deploy_Project:
        runs-on: ubuntu-latest
        steps: 
            - run: mvn -version
            - run: ls ${{ github.workspace }}
            - run: ${{ github.workspace }}/deploy.sh
            - run: ls ${{ github.workspace }}/target