
name: Release
on: [push]
jobs:
    Deploy_Project:
        runs-on: ubuntu-latest
        steps: 
            - run: mvn -version
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: |
                ls ${{ github.workspace }}
            - run: ${{ github.workspace }}/deploy.sh
            - run: ls ${{ github.workspace }}/target
            - name: Archive Binaries
              uses: actions/upload-artifact@v2
              with:
                name: pact-doc
                path: ${{ github.workspace }}/target/pact-doc.jar
            - name: pact-doc
              with:
                name: pact-doc
                path: ${{ github.workspace }}/target/run.sh
              